site_name: pyeio
site_url: https://harttraveller.github.io/pyeio
repo_name: harttraveller/pyeio
repo_url: https://github.com/harttraveller/pyeio

plugins:
- search

theme:
  name: material
  logo: static/pyeio.png
  favicon: static/pyeio.png
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
  - navigation.tracking
  - navigation.instant
  - search.suggest
  - search.share
  - content.code.copy
  - content.code.annotate
  - header.autohide
  - navigation.footer
  - navigation.tabs

extra:
  generator: false

extra_css:
- static/extra.css

markdown_extensions:
- md_in_html
- admonition
- attr_list
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true

nav:
- About: "index.md"