site_name: pyeio

plugins:
- search

theme:
  name: material
  logo: assets/pyeio-small.png
  favicon: assets/pyeio-small.png
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
  - navigation.tracking
  - navigation.instant
  - search.suggest
  - search.share
  - content.code.copy
  - content.code.annotate
  - header.autohide
  - navigation.footer
  - navigation.tabs

extra:
  generator: false

extra_css:
- stylesheets/extra.css

markdown_extensions:
- md_in_html
- admonition
- attr_list
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true


nav:
- Introduction: "index.md"
- Installation: "installation.md"
- Examples: "examples.md"
- Formats: "formats.md"
